eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8084/eureka/
  instance:
    prefer-ip-address: true
    
spring:
  application:
    name: Config-prod
